### ISSUE TITLE
Code compliance for generated project in Eclipse

### ISSUE THREAD

**Issue by davidglevy** [ggear/cloudera-framework#2]
After generating and building the example project, I imported it into eclipse. I found that I needed to add the following to the plugins to get the code compliance up (I built against JDK 1.8):

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
```

**Comment by ggear** [comment]
Thanks @davidglevy, getting with the times I have updated the codebase for Java 8 with 5509ff9ae4a66263298ee39567c99b7397e1b7c1 and destined for cloudera-framework-1.5.2-cdh5.10.1, better late than never!
